apiVersion: v1
kind: Pod
metadata:
  name: composer-d
  namespace: databases
spec:
  containers:
  - name: composer
    image: composer:2.2.7
    workingDir: /app
    command: ["composer"]
    args: ["install", "--optimize-autoloader", "--no-dev"]
    volumeMounts:
    - name: php-pvc
      mountPath: /app
      subPath: ./uismarketapp
  volumes:
  - name: php-pvc
    persistentVolumeClaim:
      claimName: pvc-uismarket
