apiVersion: v1
kind: Pod
metadata:
  name: composer
spec:
  containers:
  - name: composer
    image: composer:2.2.7
    workingDir: /app
    command: ["composer"]
    args: ["install", "--ignore-platform-reqs", "--no-scripts"]
    volumeMounts:
    - name: php-pvc
      mountPath: /app
      subPath: ./uismarketapp
  volumes:
  - name: php-pvc
    persistentVolumeClaim:
      claimName: pvc-uismarket-app
