apiVersion: v1
kind: ConfigMap
metadata:
    name: default-config
data:
    config: |
        server {
          listen [::]:80;
          listen 80 default_server;
          server_name _;
          root /app/public;
          index  index.php index.html index.htm;
          access_log /var/log/nginx/access.log  main;
          error_log /var/log/nginx/error.log  info;
          disable_symlinks off;

          add_header X-Frame-Options "SAMEORIGIN";
          add_header X-XSS-Protection "1; mode=block";
          add_header X-Content-Type-Options "nosniff";

          index index.html index.htm index.php;

          charset utf-8;

          location / {
              try_files $uri $uri/ /index.php?$query_string;
          }

          location = /favicon.ico { access_log off; log_not_found off; }
          location = /robots.txt  { access_log off; log_not_found off; }

          error_page 404 /index.php;

          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              if (!-f $document_root$fastcgi_script_name) {
                return 404;
              }
              fastcgi_pass php:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include /etc/nginx/fastcgi_params;
          }

          location ~ /\.(?!well-known).* {
              deny all;
          }
        }
