apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "my-load-balancer-01"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
