apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-deployment
  namespace: databases
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: 'getmeili/meilisearch:v0.26.0'
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: meilisearch-pvc
              mountPath: /data.ms
      volumes:
        - name: meilisearch-pvc
          persistentVolumeClaim:
            claimName: pvc-uismarket
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
  namespace: databases
spec:
  type: NodePort
  selector:
    app: meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
      nodePort: 30001
