apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: databases
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: databases
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysqldb
          image: "mysql/mysql-server:8.0"
          ports:
            - protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: base-secret
                  key: MYSQL_PASSWORD #'=THds%z(K/K~~4N3'
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: base-secret
                  key: MYSQL_DATABASE #uismarket
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: base-secret
                  key: MYSQL_USER #AlexJenn2022
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: base-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
              subPath: ./mysql
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: pvc-uismarket
