apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: databases
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.4-alpine
          ports:
            - containerPort: 80
          volumeMounts:
          - name: php-pvc
            mountPath: /app
            subPath: ./uismarketapp
          - name: config
            mountPath: "/etc/nginx/conf.d/default.conf"
            subPath: "default.conf"
      volumes:
      - name: php-pvc
        persistentVolumeClaim:
          claimName: pvc-uismarket
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: "config"
            path: "default.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: databases
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
