apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxp-deployment
  labels:
    app: nginxp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxp
  template:
    metadata:
      labels:
        app: nginxp
    spec:
      containers:
      - name: nginxp
        image: nginx:1.16
        ports:
        - containerPort: 80
