apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxdb
          image: nginx:1.21.4-alpine
          ports:
            - containerPort: 80
          volumeMounts:
          - name: php-pvc
            mountPath: /app
            subPath: ./uismarketapp
          - name: config
            mountPath: "/etc/nginx/nginx.conf"
            subPath: "nginx.conf"
          - name: default
            mountPath: "/etc/nginx/conf.d/default.conf"
            subPath: "default.conf"
      volumes:
      - name: php-pvc
        persistentVolumeClaim:
          claimName: pvc-uismarket-app
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: "config"
            path: "nginx.conf"
      - name: default
        configMap:
          name: default-config
          items:
          - key: "config"
            path: "default.conf"
