apiVersion: v1
kind: Pod
metadata:
  name: node-16
spec:
  containers:
  - name: nodejs
    image: node:16.14.0-alpine
    workingDir: /app
    volumeMounts:
    - name: php-pvc
      mountPath: /app
      subPath: ./uismarketapp
  volumes:
  - name: php-pvc
    persistentVolumeClaim:
      claimName: pvc-uismarket-app
