apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: phpdb
          image: 'alexiscaceres99/php-uismarket:1.1'
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: php-pvc
              mountPath: /app
              subPath: ./uismarketapp
            - name: config
              mountPath: "/usr/local/etc/php-fpm.d/www.conf"
              subPath: "www.conf"
            - name: env
              mountPath: "/app/.env"
              subPath: ".env"
      volumes:
        - name: php-pvc
          persistentVolumeClaim:
            claimName: pvc-uismarket-app
        - name: config
          configMap:
            name: php-config
            items:
            - key: config
              path: "www.conf"
        - name: env
          configMap:
            name: env-config
            items:
            - key: "config"
              path: ".env"
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: ClusterIP
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 9000
