apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmindb
        image: phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: mysql-service
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: phpmyadmin-service
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: phpmyadmin
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: phpmyadmin
#   annotations:
#     kubernetes.digitalocean.com/load-balancer-id: "uis-market-load-balancer"
#     service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
#     service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
# spec:
#   type: LoadBalancer
#   selector:
#     app: phpmyadmin
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
