apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uismarket-app
  namespace: app
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
