apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uismarket-app
  namespace: databases
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
