apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-state
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: "redis-service"
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redisdb
          image: "redis:6.2.6-alpine3.15"
          ports:
            - protocol: TCP
              containerPort: 6379
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
              subPath: ./redis
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: pvc-uismarket
